apiVersion: zhanggq.tech.zhanggq.tech/v1beta1
kind: App
metadata:
  name: app-sample
spec:
  # TODO(user): Add fields here
  image: nginx:latest
  replicas: 1
  enable_ingress: true
  enable_service: true
